blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/montanarograziano/spark_plan_viz/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://github.com/montanarograziano/spark_plan_viz#readme
    about: Read the documentation and examples
